version: "3.7"
services:

# APIs service
  node:
    image: "node:current"
    privileged: true
    tty: true
    stdin_open: true
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=devlopment
    volumes:
      - ./src/:/home/node/app
    ports:
      - "8081:8081"
    command: "npm start"
